${RV32I_HOME}/src/pipelined/control_logic.sv
${RV32I_HOME}/src/pipelined/forwarding_unit.sv
${RV32I_HOME}/src/pipelined/hazard_detection.sv
${RV32I_HOME}/src/pipelined/memory.sv
${RV32I_HOME}/src/pipelined/RegFile.sv
${RV32I_HOME}/src/pipelined/predictor/branch_prediction.sv
${RV32I_HOME}/src/pipelined/predictor/btb.sv
${RV32I_HOME}/src/pipelined/predictor/gshare.sv
${RV32I_HOME}/src/pipelined/predictor/local_predictor.sv
${RV32I_HOME}/src/pipelined/predictor/one_bit_predictor.sv
${RV32I_HOME}/src/pipelined/predictor/saturated_adder.sv
${RV32I_HOME}/src/pipelined/predictor/saturated_counter.sv
${RV32I_HOME}/src/pipelined/predictor/tournament_predictor.sv
${RV32I_HOME}/src/pipelined/predictor/two_bit_predictor.sv
${RV32I_HOME}/src/pipelined/regs/EX_MEM_regs.sv
${RV32I_HOME}/src/pipelined/regs/ID_EX_regs.sv
${RV32I_HOME}/src/pipelined/regs/IF_ID_regs.sv
${RV32I_HOME}/src/pipelined/regs/MEM_WB_regs.sv
${RV32I_HOME}/src/pipelined/stages/EX.sv
${RV32I_HOME}/src/pipelined/stages/ID.sv
${RV32I_HOME}/src/pipelined/stages/IF.sv
${RV32I_HOME}/src/pipelined/stages/MEM.sv
${RV32I_HOME}/src/pipelined/stages/WB.sv
${RV32I_HOME}/src/pipelined.sv
